name: ring
main: com.gmail.wplct1.ring.ring
version: 0.0.1
author: wplct
commands:
  ring:
    description:
    permission: ring.admin
    permission-message: 你没有权限
permissions:
  ring.admin:
    default: op